sudo: required
services:
  - docker

before_install:
  - docker build -t elenakves/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true elenakves/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-065056623816"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
