version: '3'
services:
  web:
    #command: tail -f /dev/null
    tty: true
    build:
     context: .
     dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
